name: feature-pipeline
on: workflow_dispatch
  # push:

jobs:
  # Job name
  feature-pipeline:
    if: github.ref_name != 'main'
    uses: javeed-mohd/workflows/.github/workflows/nodejs-feature-pipeline.yaml@main
    with:
      project: 'roboshop'
      component: 'catalogue'
    secrets: inherit            # It is used while calling reusable workflows, these are used because reusable workflows cannot access secrets directly.